- name: remove instances
  hosts: all
  gather_facts: False
  connection: local
  become: no
  vars:
    provider: vmware
  vars_files:
    - node-config/nodes-{{ provider }}.yml

  roles:
    - role: ansible-role-{{ provider }}
      role_action: deprovision
      delegate_to: localhost
      run_once: yes